In [1]:
import numpy as np

In [9]:
x = np.load('../processed_data/eval/ligands/0101.pk')
x = x[0]

In [10]:
np.nonzero(x)

(array([ 8,  8,  8, ..., 18, 18, 18]),
 array([11, 12, 12, ..., 15, 16, 16]),
 array([13, 12, 13, ..., 12, 10, 11]))